import type { Metadata } from 'next';
import { Barlow, Imbue } from 'next/font/google';
import { hasLocale, NextIntlClientProvider } from 'next-intl';
import '@/styles/globals.css';
import { notFound } from 'next/navigation';
import { ReactNode } from 'react';
import { Header } from '@/components/Header/Header';
import { LanguageSwitcher } from '@/components/LanguageSwitcher/LanguageSwitcher';
import { routing } from '@/i18n/routing';
import { cn } from '@/libs/cn';

const imbue = Imbue({
  subsets: ['latin'],
  variable: '--font-imbue',
});

const barlow = Barlow({
  display: 'swap',
  subsets: ['latin'],
  variable: '--font-barlow',
  weight: ['300', '500'],
});

export const metadata: Metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App',
};

type Props = {
  children: ReactNode;
  params: Promise<{ locale: string }>;
};

export default async function LocaleLayout({ children, params }: Props) {
  const { locale } = await params;

  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  return (
    <html
      className={`${imbue.variable} ${barlow.className} antialiased`}
      lang={locale}
      translate="no"
    >
      <body
        className={cn('min-h-svh pt-5 flex flex-col', 'md:pt-10', '2xl:pt-15')}
      >
        <NextIntlClientProvider>
          <Header />

          {children}

          <LanguageSwitcher className="hidden lg:block" />
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
