import type { Metadata } from 'next';
import { Barlow, Imbue } from 'next/font/google';
import { hasLocale, NextIntlClientProvider } from 'next-intl';
import '../globals.css';
import { notFound } from 'next/navigation';
import { ReactNode } from 'react';
import { Header } from '@/app/components/Header/Header';
import { LanguageSwitcher } from '@/app/components/LanguageSwitcher/LanguageSwitcher';
import { routing } from '@/i18n/routing';

const imbue = Imbue({
  subsets: ['latin'],
  variable: '--font-imbue',
});

const barlow = Barlow({
  display: 'swap',
  subsets: ['latin'],
  variable: '--font-barlow',
  weight: ['300', '500'],
});

export const metadata: Metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App',
};

type Props = {
  children: ReactNode;
  params: Promise<{ locale: string }>;
};

export default async function LocaleLayout({ children, params }: Props) {
  const { locale } = await params;

  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  return (
    <html
      className={`${imbue.variable} ${barlow.className} antialiased`}
      lang={locale}
    >
      <body className="min-h-screen p-10 flex flex-col gap-10">
        <NextIntlClientProvider>
          <Header />

          <main className="relative grow">{children}</main>

          <LanguageSwitcher />
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
